### ISSUE TITLE
can't load script

### ISSUE THREAD

**Issue by nakumiayumu144** [uezo/ChatdollKit#217]
i am using Unity 2021.3.21f1
![image](https://user-images.githubusercontent.com/127565115/227733656-54bdc938-281e-47b4-bc9b-294515fe6e68.png)

**Comment by uezo** [comment]
Hi @nakumiayumu144 ,
You need JSON.NET.

1. Open Package Manager
1. Add package from git URL
1. com.unity.nuget.newtonsoft-json@3.0

Also I found that we are no longer able to get it from Asset Store. I will fix README.

**Comment by nakumiayumu144** [comment]
thanks its working now
