### ISSUE TITLE
Demo Error

### ISSUE THREAD

**Issue by royshan** [uezo/ChatdollKit#230]
Dear Uezo,

Thank you very much for making such an interesting kit!

When I try to play the demos, e.g. DemoEcho scene, I ran into a strange error as follows:
```
NullReferenceException: Object reference not set to an instance of an object
ChatdollKit.Model.ModelController.UpdateAnimation () (at Assets/ChatdollKit/Scripts/Model/ModelController.cs:400)
ChatdollKit.Model.ModelController.Update () (at Assets/ChatdollKit/Scripts/Model/ModelController.cs:103)
```

I have set up the animator in the Model Controller and used the dependencies as you instructed. What could go wrong?

**Comment by uezo** [comment]
Hi @royshan , I created another issue to discuss face expression 👉 #232 
Basically you should configure the face named `Neutral`. However, even if `Neutral` is missing, this should not be handled as a critical error but as a warning.
