### ISSUE TITLE
Voice input is not possible

### ISSUE THREAD

**Issue by moriya2535** [uezo/ChatdollKit#293]
Thank you for sharing this wonderful tool!

I tried running it with Unity, but I can't input voice chat.
It runs on Open AI, and it can chat properly with text input.
I also made sure to give Unity permission to access the microphone on Windows.
The attached image is the Console log, and it appears that the built-in microphone is enabled and there is no problem.
![スクリーンショット 2024-06-05 093820](https://github.com/uezo/ChatdollKit/assets/104309749/e241fff3-1aec-4dde-9ef2-339cf5ce636c)

However, even when I talk, the Audio Clipping in Statistics remains at 0% and the green bar does not move.
![スクリーンショット 2024-06-05 095017](https://github.com/uezo/ChatdollKit/assets/104309749/4e3b3b67-be9d-4f30-b365-fd0c2e0c91f5)

For reference, I have also pasted the log when Debug Sampling Data and Print Devices were checked in Chatdoll Microphone (Script).
![スクリーンショット 2024-06-05 095232](https://github.com/uezo/ChatdollKit/assets/104309749/f54bb824-8784-4bf6-8686-40ccbc21a8d6)
![スクリーンショット 2024-06-05 094932](https://github.com/uezo/ChatdollKit/assets/104309749/d5fd7a05-d31e-486e-93af-cbc5d0cdbea0)

What points should I check to enable voice input?
I would appreciate it if you could give me some advice.

In addition, I have confirmed that voice input can be performed via Chrome in the following demo.
https://unagiken.com/chatdollkit/playground/index.html

**Comment by moriya2535** [comment]
In addition, I have confirmed that voice input can be performed via Chrome in the following demo.
https://unagiken.com/chatdollkit/playground/index.html

**Comment by uezo** [comment]
Hi @moriya2535 ,
If you are running the demo, bring the handle on the microphone slider to the right edge and say something to the app. That means microphone handles without the noise filter.

**Comment by moriya2535** [comment]
Hello @uezo 
Thank you for your reply.
I tried to slide the green bar to the right as shown in the attached image and speak, but I could not communicate with ChatdollKit. The green circle is blinking.
![image](https://github.com/uezo/ChatdollKit/assets/104309749/76ab5652-0bc0-43e1-8139-af115a697e39)

I am using the following Assets.

ChatdollKit_0.7.2.unitypackage
ChatdollKit_Demo_0.7.2.unitypackage
ChatdollKit_VRMExtension_0.7.1.unitypackage
uLipSync-v3.1.1.unitypackage
UniTask.2.5.4.unitypackage
UniVRM-0.89.0_9470.unitypackage
