### ISSUE TITLE
An error occurs when a character tries to speak on WebGL

### ISSUE THREAD

**Issue by moriya2535** [uezo/ChatdollKit#295]
Hello,

I tried building ChatdollKit into WebGL based on this page (Usage 1~3).
https://github.com/uezo/uLipSyncWebGL

The build was successful and ChatdollKit started on chrome (browser).
When I spoke with Wake word, the character tried to respond, but it makes a buzzing noise and no text is displayed.
( It seems that voice recognition is successful as it does not respond to anything other than the Wake word.)

After that, Listening... was displayed.  I tried to talk to the character, but it crashed with an error before the character spoke.
( It's crashing in framework.js)

It seems to crash when the character speaks.  (something wrong with the speaker or GPT connection? )

I have confirmed that ChatdollKitDemo works correctly on Unity.

-----
![image](https://github.com/uezo/ChatdollKit/assets/104309749/e72856bf-3e01-467f-8f8a-348c44ded78d)

 I said "It is good weather".  Chatdollkit can also correctly recognize my speech.
 However, It is sending a chunk to Gemini and it seems to be crashing with an error that there is no API key.
I have registered an Open AI key. If I register the Gemini key, will it solve the problem?

Any help is appreciated.

**Comment by uezo** [comment]
Hi @moriya2535 ,
If you are using GeminiServiceWebGL, the API key issued at Google AI Studio is required.

**Comment by moriya2535** [comment]
Hi @uezo 
Thank you for your reply.
When I set the Gemini key in addition to the OpenAI key, it no longer stopped due to an error.
And I changed the code below in OpenAITTSLoader.cs ,because it couldn't play mp3.
{ "response_format", "wav" },
Then, the sound started coming out.

But sound was so slow that I couldn't hear it.
I tried the following to increase the speed of sound playback, but it didn't improve.
- Changed the frequency of PCMToAudioClip from 8000 to 16000
・Speed ​​changed from 1.0f to 2.5f

Do you know how to get the character's voice to play at normal speed?

**Comment by uezo** [comment]
Hi @moriya2535 ,
Use the font that includes Japanese like IBM Plex Sans JP, Noto Sans or something like that.

**Comment by moriya2535** [comment]
Thank you for your quick reply. 
I will try based on your answer. 
thank you

**Comment by moriya2535** [comment]
Hi @uezo,
Thanks to you, I can display Japanese text.
Thank you for your kind support.
