### ISSUE TITLE
iOS build failed

### ISSUE THREAD

**Issue by mazotav** [uezo/ChatdollKit#306]
Hi,
i've got iOS build succeed on Unity but failed on Xcode.
How can I solve this issue? Thanks!!

![2024-06-24 6 40の画像](https://github.com/uezo/ChatdollKit/assets/173637074/65bc8b8d-4473-4f0a-9046-32d65c7f8b4e)

**Comment by uezo** [comment]
Hi @mazotav ,
Which version are you using? Update ChatdollKit to the latest version. Or, delete `ChatGPT*.cs` in Scripts/Dialog.
