### ISSUE TITLE
Bug GateboxSDK

### ISSUE THREAD

**Issue by tmdgroupid** [uezo/ChatdollKit#313]
Hi, i have a problem my project virtual assistant usig chatdollkit sdk. my problem is: Assets\ChatdollKit\Extension\Gatebox\Scripts\GateboxApplication.cs(8,30): error CS0246: The type or namespace name 'GateboxSDK' could not be found (are you missing a using directive or an assembly reference?) and Assets\ChatdollKit\Extension\Gatebox\Scripts\GateboxApplication.cs(3,7): error CS0246: The type or namespace name 'com' could not be found (are you missing a using directive or an assembly reference?)
![image](https://github.com/uezo/ChatdollKit/assets/156943299/84cb58f1-c280-46c3-bafa-5091afa299e8)

**Comment by uezo** [comment]
Hi @tmdgroupid ,
Delete `Assets\ChatdollKit\Extension\Gatebox` if you don't build app for Gatebox.
Otherwise, install Gatebox SDK.

**Comment by tmdgroupid** [comment]
> Hi @tmdgroupid , Delete `Assets\ChatdollKit\Extension\Gatebox` if you don't build app for Gatebox. Otherwise, install Gatebox SDK.

Thanks for answer
