### ISSUE TITLE
Animation response

### ISSUE THREAD

**Issue by brycelynch** [uezo/ChatdollKit#324]
Why aren't my animations firing off?  I think I have it set up right.  Is there another step I'm missing?

<img width="774" alt="Screenshot 2024-08-20 at 12 21 47 PM" src="https://github.com/user-attachments/assets/8a05b072-78ac-4291-abe6-373bbf9f19a8">
<img width="485" alt="Screenshot 2024-08-20 at 12 20 21 PM" src="https://github.com/user-attachments/assets/68fb09b5-88c8-4d07-b296-47ae9819aa50">

**Comment by uezo** [comment]
Hi @brycelynch,

To autonomously use animation in a conversation, follow these steps:

1. Create an Animator Controller with animation clips and transitions. (Maybe you've already done this👍)
2. Define the mapping between the animation names and the corresponding values to trigger the transitions.
    See [this example](https://github.com/uezo/ChatdollKit/blob/master/Demo/Scripts/Main.cs#L93).
3. Inform ChatGPT of the list of available animation names in the system prompt.
    See [this example](https://github.com/uezo/ChatdollKit/blob/master/Demo/Demo.unity#L1801).

**Comment by brycelynch** [comment]
Thanks for the reply.  This tool is awesome btw.   :)

I believe I have that all set up correctly.   I've been mostly borrowing from what you've done in the demo.  For a sanity check, I used the demo scene and I get the same error that waving_arm is not registered -- I'm only testing this one animation to see how everything is supposed to work.  I tried changing the name of the wave_arm animation thinking that might be the issue?   Do you think it's because I've just renamed the animation to match the corresponding values in your example.  I'm also using your system prompt.  Here are some screen grabs: 

<img width="1681" alt="Screenshot 2024-08-20 at 5 04 02 PM" src="https://github.com/user-attachments/assets/4a621544-a0f5-47cc-b102-bd7a5d07048c">

<img width="1671" alt="Screenshot 2024-08-20 at 5 05 32 PM" src="https://github.com/user-attachments/assets/36280058-688d-4eaa-8ca0-e3ec917fefc2">

**Comment by brycelynch** [comment]
I think I figured out what I was doing wrong.  I had turned off main.cs and that was what was causing the unregistered errors.  Thanks again.  :)
