### ISSUE TITLE
Error when using Google TTS Loader

### ISSUE THREAD

**Issue by peltwwb** [uezo/ChatdollKit#352]
I am using version 0.8.1. 

Upon attaching the Google TTS Loader, the system responds to the wake word; however, the “listening…” does not appear afterward.

The console shows the following error:

Error occurred while processing text-to-speech voice: Length of created clip must be larger than 0

In contrast, the OpenAI TTS Loader functions without any issues.

I would appreciate your help in resolving this issue.

**Comment by uezo** [comment]
Hi @peltwwb ,

That message shows that Google TTS service got no texts to speech.
You can debug by inserting the following block:

```csharp
        protected override async UniTask<AudioClip> DownloadAudioClipAsync(Voice voice, CancellationToken token)
        {
            if (token.IsCancellationRequested) { return null; };

            if (string.IsNullOrEmpty(ApiKey) || string.IsNullOrEmpty(Language))
            {
                Debug.LogError("API Key or Language are missing from GoogleTTSLoader");
            }

            // Insert this block
            if (string.IsNullOrEmpty(voice.Text.Trim()))
            {
                Debug.Log($"No texts to speak");
                return null;
            }

```

**Comment by peltwwb** [comment]
Thank you! The problem has been solved!

**Comment by uezo** [comment]
@peltwwb 👍

I will update some TTSLoaders that have same issue.
